import { ChakraProvider } from "@chakra-ui/react"
import { theme } from "@/config/theme"
import { franklinGothicBookItalic, franklinGothicBook, franklinGothicDemiCond, franklinGothicMediumCond, inter, openSans } from "./fonts"


export const metadata = {
  title: {
    default: `Carlo's e-commerce Website`,
    template: `%s | Carlo's website`,
  },
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${openSans.variable} ${inter.variable} ${franklinGothicBookItalic.variable} ${franklinGothicDemiCond.variable} ${franklinGothicMediumCond.variable} ${franklinGothicBook.variable}`}>
      <body>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  )
}
