import { Inter } from "next/font/google"
import { ChakraProvider, Flex, Text } from "@chakra-ui/react"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: {
    default: `Carlo's e-commerce Website`,
    template: `%s | Carlo's website`,
  },
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Flex justifyContent={'center'} gap={10} p={4} >
            <Link href={'/'}><Text>Home</Text></Link>
            <Link href={'/shop'}><Text>Shop</Text></Link>
            <Link href={'/cart'}><Text>Cart</Text></Link>
            <Link href={'/stripe'}><Text>Stripe APIs</Text></Link>
          </Flex>
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
