import { Flex, Heading } from "@chakra-ui/react"
import React from "react"

export const generateMetadata = ({params}) => {
  console.log('asdf', { params })
  return {
    title: `Product ${params.productName}`,
    description: 'this is generated by nextJS',
  }
}

const ProductName = ({ params }) => {
  console.log({ params })
  return (
    <Flex flexDir={'column'}>
      <Heading>Product name: {params.productName}</Heading>
    </Flex>
  )
}

export default ProductName
